name: canary_admin
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase: ^7.3.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.5.1
  get_it: ^4.0.2
  provider: ^4.1.2
  image_picker_saver: ^0.3.0
  uuid: ^2.0.4
  async: ^2.4.1
  http: ^0.12.1
  image: ^2.1.11
  image_picker: ^0.6.6+4
  cached_network_image: ^2.2.0+1
  datetime_picker_formfield: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bg_sidebar.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Normal
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: Bold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: Italic
      fonts:
        - asset: fonts/Roboto-Italic.ttf
    - family: Light
      fonts:
        - asset: fonts/Roboto-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
